/**
 * Türkiye 81 İl Detaylı Veri Seti
 * Siyasi Harita, Gezi Rehberi, Meşhur Lezzetler ve Not Sistemi için
 */

const TURKEY_REGIONS = {
    marmara: {
        id: "marmara",
        name: "Marmara Bölgesi",
        color: "#3b82f6", // Mavi ton
        lightColor: "#dbeafe",
        badge: "🌊 Marmara"
    },
    ege: {
        id: "ege",
        name: "Ege Bölgesi",
        color: "#10b981", // Zümrüt yeşili
        lightColor: "#d1fae5",
        badge: "🌿 Ege"
    },
    akdeniz: {
        id: "akdeniz",
        name: "Akdeniz Bölgesi",
        color: "#f59e0b", // Kehribar sarı / turuncu
        lightColor: "#fef3c7",
        badge: "☀️ Akdeniz"
    },
    icanadolu: {
        id: "icanadolu",
        name: "İç Anadolu Bölgesi",
        color: "#8b5cf6", // Mor ton
        lightColor: "#ede9fe",
        badge: "🌾 İç Anadolu"
    },
    karadeniz: {
        id: "karadeniz",
        name: "Karadeniz Bölgesi",
        color: "#059669", // Koyu yeşil
        lightColor: "#a7f3d0",
        badge: "🌲 Karadeniz"
    },
    doguanadolu: {
        id: "doguanadolu",
        name: "Doğu Anadolu Bölgesi",
        color: "#ef4444", // Kırmızı / Dağ tonu
        lightColor: "#fee2e2",
        badge: "🏔️ Doğu Anadolu"
    },
    guneydoguanadolu: {
        id: "guneydoguanadolu",
        name: "Güneydoğu Anadolu Bölgesi",
        color: "#d97706", // Sıcak terrakota
        lightColor: "#fde68a",
        badge: "🏛️ Güneydoğu"
    }
};

const PROVINCES_DATA = {
    "01": {
        plate: "01",
        id: "adana",
        name: "Adana",
        regionId: "akdeniz",
        areaCode: "322",
        population: "2.274.000",
        altitude: "23 m",
        tagline: "Güneşin ve Lezzetin Başkenti",
        highlights: ["Taşköprü", "Varda Köprüsü", "Sabancı Merkez Camii", "Anavarza Antik Kenti", "Seyhan Baraj Gölü"],
        foods: ["Adana Kebabı", "Şalgam Suyu", "Bici Bici", "Analı Kızlı", "Halka Tatlısı"],
        desc: "Bereketli Çukurova topraklarının merkezinde yer alan Adana, binlerce yıllık tarihi Taşköprü'sü, eşsiz mutfak kültürü ve sıcak Akdeniz insanıyla Türkiye'nin en canlı metropollerinden biridir.",
        bestTime: "Ekim - Mayıs ayları arası festival ve gurme turları için idealdir."
    },
    "02": {
        plate: "02",
        id: "adiyaman",
        name: "Adıyaman",
        regionId: "guneydoguanadolu",
        areaCode: "416",
        population: "635.000",
        altitude: "672 m",
        tagline: "Tanrıların Göğe Değdiği Zirve: Nemrut",
        highlights: ["Nemrut Dağı Milli Parkı", "Cendere Köprüsü", "Perre Antik Kenti", "Karakuş Tümülüsü", "Arsemia Ören Yeri"],
        foods: ["Adıyaman Çiğköftesi", "Basalla", "Besni Tavası", "Buhara Pilavı", "Dövmeç"],
        desc: "UNESCO Dünya Mirası Nemrut Dağı'nda Kommagene Krallığı'nın devasa heykellerine ev sahipliği yapan Adıyaman, antik çağların gizemini günümüze taşıyan benzersiz bir kültür merkezidir.",
        bestTime: "Gündoğumu ve günbatımı manzaraları için Mayıs - Ekim ayları en uygun zamandır."
    },
    "03": {
        plate: "03",
        id: "afyonkarahisar",
        name: "Afyonkarahisar",
        regionId: "ege",
        areaCode: "272",
        population: "750.000",
        altitude: "1.021 m",
        tagline: "Termal Başkent, Tarih ve Lezzetin Kavşağı",
        highlights: ["Afyon Kalesi", "Frig Vadisi", "Ulu Cami (Ahşap Direkli)", "Tarihi Bedesten", "Gazlıgöl Kaplıcaları"],
        foods: ["Afyon Sucuğu", "Hakiki Manda Kaymağı", "Afyon Lokumu", "Bükme", "Haşhaşlı Ekmek"],
        desc: "Zaferin ve Frig medeniyetinin kalbi olan Afyon, şifalı termal suları, binlerce yıllık volkanik kale manzarası ve tescilli zengin gastronomi kültürü ile ünlüdür.",
        bestTime: "Termal tatiller için sonbahar ve kış; Frig vadisi yürüyüşleri için ilkbahar önerilir."
    },
    "04": {
        plate: "04",
        id: "agri",
        name: "Ağrı",
        regionId: "doguanadolu",
        areaCode: "472",
        population: "510.000",
        altitude: "1.632 m",
        tagline: "Efsanelerin Dağı ve İshak Paşa Sarayı",
        highlights: ["Ağrı Dağı (5.137 m)", "İshak Paşa Sarayı", "Doğubayazıt Kalesi", "Meteor Çukuru", "Diyadin Kanyonu"],
        foods: ["Abdigör Köftesi", "Ayranaşı", "Alabalık", "Haşıl", "Selek"],
        desc: "Türkiye'nin çatısı olan heybetli Ağrı Dağı ve kartal yuvası gibi ovaya bakan eşsiz İshak Paşa Sarayı ile büyüleyen Ağrı, Doğu'nun masalsı kapısıdır.",
        bestTime: "Dağcılık ve saray ziyaretleri için Temmuz - Eylül ayları idealdir."
    },
    "05": {
        plate: "05",
        id: "amasya",
        name: "Amasya",
        regionId: "karadeniz",
        areaCode: "358",
        population: "340.000",
        altitude: "411 m",
        tagline: "Şehzadeler Şehri ve Ferhat ile Şirin'in Diyarı",
        highlights: ["Kral Kaya Mezarları", "Harşena Kalesi", "Yalıboyu Evleri", "Ferhat ile Şirin Aşıklar Müzesi", "Boraboy Gölü"],
        foods: ["Amasya Misket Elması", "Amasya Çöreği", "Baklalı Dolma", "Toyga Çorbası", "Keşkek"],
        desc: "Yeşilırmak kıyısına inci gibi dizilen Osmanlı yalıboyu konakları, dik kayalıklara oyulmuş Pontus krallarının mezarlarıyla Amasya, yaşayan bir açık hava müzesidir.",
        bestTime: "İlkbahar ve sonbahar aylarında Yeşilırmak boyundaki akşam yürüyüşleri muhteşemdir."
    },
    "06": {
        plate: "06",
        id: "ankara",
        name: "Ankara",
        regionId: "icanadolu",
        areaCode: "312",
        population: "5.803.000",
        altitude: "938 m",
        tagline: "Cumhuriyetin Kalbi ve Başkent",
        highlights: ["Anıtkabir", "Ankara Kalesi", "Anadolu Medeniyetleri Müzesi", "Hamamönü", "Kocatepe Camii", "Eymir Gölü"],
        foods: ["Ankara Döneri", "Ankara Tavası", "Beypazarı Kurusu", "Çubuk Turşusu", "Simit & Kaşar"],
        desc: "Gazi Mustafa Kemal Atatürk'ün ebedi istirahatgahı Anıtkabir'e ev sahipliği yapan Ankara, Hititlerden Cumhuriyete uzanan derin tarihi ve modern dinamizmiyle Türkiye'nin başkentidir.",
        bestTime: "Kültür, müze ve sanat etkinlikleri için yılın her dönemi, özellikle Nisan - Haziran ve Eylül - Kasım uygundur."
    },
    "07": {
        plate: "07",
        id: "antalya",
        name: "Antalya",
        regionId: "akdeniz",
        areaCode: "242",
        population: "2.690.000",
        altitude: "30 m",
        tagline: "Turizmin ve Antik Çağların Akdeniz Başkenti",
        highlights: ["Kaleiçi & Hadrian Kapısı", "Aspendos Antik Tiyatrosu", "Düden & Kurşunlu Şelaleleri", "Olympos & Çıralı", "Kaş & Kaputaş Plajı"],
        foods: ["Antalya Usulü Tahinli Piyaz", "Hibeş", "Yanık Dondurma", "Toros Kavurması", "Turunç Reçeli"],
        desc: "Turkuaz koyları, Toros Dağları'nın eteklerine serpilmiş yüzlerce antik kenti ve hareketli sahil yaşamıyla Antalya, dünyanın en gözde tatil merkezlerinden biridir.",
        bestTime: "Deniz tatili için Mayıs - Ekim; antik kent ve Likya yolu yürüyüşleri için Mart - Mayıs ayları kusursuzdur."
    },
    "08": {
        plate: "08",
        id: "artvin",
        name: "Artvin",
        regionId: "karadeniz",
        areaCode: "466",
        population: "172.000",
        altitude: "345 m",
        tagline: "Yeşilin ve Bulutların Dans Ettiği Saklı Cennet",
        highlights: ["Borçka Karagöl", "Şavşat Karagöl", "Mençuna Şelalesi", "Çoruh Kanyonu & Zipline", "Atatepe Dev Atatürk Anıtı"],
        foods: ["Kuymak", "Laz Böreği", "Karalahana Sarması", "Puçuko", "Şavşat Ketesi"],
        desc: "Göz alabildiğine uzanan bakir yaylaları, zümrüt renkli krater gölleri ve derin kanyonlarıyla Artvin, doğaseverler için adeta yeryüzündeki bir masal dünyasıdır.",
        bestTime: "Yayla şenlikleri ve doğa fotoğrafçılığı için Haziran - Eylül ayları en güzel dönemdir."
    },
    "09": {
        plate: "09",
        id: "aydin",
        name: "Aydın",
        regionId: "ege",
        areaCode: "256",
        population: "1.150.000",
        altitude: "64 m",
        tagline: "Gökyüzünün Altındaki En Güzel Yeryüzü",
        highlights: ["Afrodisias Antik Kenti", "Didim Apollon Tapınağı", "Kuşadası Güvercinada", "Dilek Yarımadası Milli Parkı", "Milet Antik Kenti"],
        foods: ["Aydın Kuru İnciri", "Çine Köftesi", "Zeytinyağlı Enginar", "Paşa Böreği", "Kabak Tatlısı"],
        desc: "Herodot'un 'gökyüzünün altındaki en güzel yeryüzü' diye andığı Aydın, zeytin ve incir ağaçlarıyla bezenmiş ovaları ve Afrodisias gibi UNESCO harikalarıyla Ege'nin parlayan yıldızıdır.",
        bestTime: "Tarih gezileri için ilkbahar ve sonbahar; sahil tatili için yaz ayları tavsiye edilir."
    },
    "10": {
        plate: "10",
        id: "balikesir",
        name: "Balıkesir",
        regionId: "marmara",
        areaCode: "266",
        population: "1.260.000",
        altitude: "145 m",
        tagline: "İki Denize Kıyısı Olan Oksijen Deposu",
        highlights: ["Cunda Adası (Ayvalık)", "Şeytan Sofrası", "Kaz Dağları Milli Parkı", "Manyas Kuş Cenneti", "Erdek & Avşa Adası"],
        foods: ["Höşmerim Tatlısı", "Susurluk Tostu & Ayranı", "Ayvalık Tostu", "Balıkesir Kuzu Eti", "Zeytinyağı"],
        desc: "Hem Ege'ye hem Marmara'ya kıyısı olan Balıkesir, Kaz Dağları'nın bol oksijenli havası, Cunda'nın taş sokakları ve meşhur lezzetleriyle dopdolu bir rotadır.",
        bestTime: "Yazın deniz tatili, ilkbahar ve sonbaharda Kaz Dağları doğa kampları için çok uygundur."
    },
    "11": {
        plate: "11",
        id: "bilecik",
        name: "Bilecik",
        regionId: "marmara",
        areaCode: "228",
        population: "230.000",
        altitude: "513 m",
        tagline: "Osmanlı'nın Doğduğu Topraklar",
        highlights: ["Şeyh Edebali Türbesi", "Söğüt Ertuğrul Gazi Türbesi", "Bilecik Saat Kulesi", "Harmankaya Kanyonu", "Kınık Şelalesi"],
        foods: ["Dağ Eriği Ekşili Çorba", "Bıldırcın Kebabı", "Nohutlu Mantı", "Bilecik Bozası", "Cevizli Lokum"],
        desc: "Osmanlı Devleti'nin temellerinin atıldığı Söğüt ve manevi mimarı Şeyh Edebali'ye ev sahipliği yapan Bilecik, derin tarihi mirası ve sakin doğasıyla öne çıkar.",
        bestTime: "Ertuğrul Gazi'yi Anma Şenlikleri (Eylül) ve ilkbahar ayları."
    },
    "12": {
        plate: "12",
        id: "bingol",
        name: "Bingöl",
        regionId: "doguanadolu",
        areaCode: "426",
        population: "285.000",
        altitude: "1.151 m",
        tagline: "Yüzen Adaların ve Şifalı Suların Şehri",
        highlights: ["Solhan Yüzen Adalar", "Buban Bacaları", "Hesarek Kayak Merkezi", "Kös Kaplıcaları", "Zağ Mağaraları"],
        foods: ["Organik Bingöl Balı", "Gömme (Gömbe)", "Mastuva", "Löl (Börek)", "Keldoş"],
        desc: "Krater gölündeki doğa mucizesi Yüzen Adalar'ı, peri bacalarını andıran Buban Bacaları ve kışın gözde Hesarek Kayak Merkezi ile Bingöl, keşfedilmeyi bekleyen bir cevherdir.",
        bestTime: "Kış sporları için Ocak - Mart; doğa turları için Mayıs - Eylül arası."
    },
    "13": {
        plate: "13",
        id: "bitlis",
        name: "Bitlis",
        regionId: "doguanadolu",
        areaCode: "434",
        population: "355.000",
        altitude: "1.545 m",
        tagline: "Nemrut Krateri ve Ahlat Selçuklu Mirası",
        highlights: ["Nemrut Krater Gölü (Dünyanın 2. büyüğü)", "Ahlat Selçuklu Meydan Mezarlığı", "Bitlis Kalesi", "İslahiye Medresesi", "Tatvan Sahili"],
        foods: ["Bitlis Büryan Kebabı", "Katıklı Dolma", "Cevizli Avşor Çorbası", "İçli Köfte", "Karakovan Balı"],
        desc: "Dünyanın ikinci büyük krater gölüne ve Türk-İslam dünyasının en büyük tarihi mezarlığı olan Ahlat Selçuklu taş işçiliğine sahip Bitlis, köklü bir medeniyet merkezidir.",
        bestTime: "Nemrut kraterinde kamp ve Ahlat ziyaretleri için Haziran - Eylül dönemi."
    },
    "14": {
        plate: "14",
        id: "bolu",
        name: "Bolu",
        regionId: "karadeniz",
        areaCode: "374",
        population: "325.000",
        altitude: "726 m",
        tagline: "Göller, Tabiat Parkları ve Aşçılar Diyarı",
        highlights: ["Yedigöller Milli Parkı", "Abant Gölü", "Gölcük Tabiat Parkı", "Kartalkaya Kayak Merkezi", "Göynük Tarihi Evleri"],
        foods: ["Mengen Pilavı", "Bolu Çikolatası", "Saray Helvası", "Kartalkaya Kebabı", "Keşli Cevizli Erişte"],
        desc: "Her mevsim ayrı bir kartpostal güzelliği sunan Abant, Gölcük ve Yedigöller'i, Osmanlı mirası Göynük konakları ve dünyaca ünlü Mengen aşçılarıyla Bolu eşsizdir.",
        bestTime: "Sonbaharda Yedigöller yaprak dökümü (Ekim-Kasım), kışın Kartalkaya kayağı."
    },
    "15": {
        plate: "15",
        id: "burdur",
        name: "Burdur",
        regionId: "akdeniz",
        areaCode: "248",
        population: "275.000",
        altitude: "950 m",
        tagline: "Türkiye'nin Maldivleri Salda ve Sagalassos",
        highlights: ["Salda Gölü", "Sagalassos Antik Kenti (Ağlasun)", "İnsuyu Mağarası", "Kibyra Antik Kenti", "Burdur Arkeoloji Müzesi"],
        foods: ["Burdur Şiş Kebabı", "Burdur Ceviz Ezmesi", "Kenevir Helvası", "Testi Kebabı", "Kabak Helvası"],
        desc: "Bembeyaz kumsalları ve turkuaz suyuyla ünlü Salda Gölü ile dağların zirvesindeki Antoninler Çeşmesi'nden su akan Sagalassos'u barındıran Burdur, Göller Yöresi'nin incisidir.",
        bestTime: "Salda ve antik kent yürüyüşleri için Mayıs - Ekim ayları."
    },
    "16": {
        plate: "16",
        id: "bursa",
        name: "Bursa",
        regionId: "marmara",
        areaCode: "224",
        population: "3.200.000",
        altitude: "155 m",
        tagline: "Yeşil Bursa: Osmanlı'nın İlk Başkenti ve Uludağ",
        highlights: ["Ulu Cami & Koza Han", "Cumalıkızık UNESCO Köyü", "Uludağ Kayak Merkezi", "Yeşil Türbe & Külliye", "Tophane Saat Kulesi"],
        foods: ["Bursa İskender Kebabı", "Kestane Şekeri", "Cantık Pidesi", "Kemalpaşa Tatlısı", "Muradiye Çorbası"],
        desc: "Osmanlı'nın ilk başkenti olan Yeşil Bursa; 600 yıllık ulu çınarları, şifalı kaplıcaları, kışın Uludağ'ı ve parmak ısırtan İskender Kebabı ile Türkiye'nin en görkemli şehirlerindendir.",
        bestTime: "Kışın Uludağ kayağı; ilkbahar ve sonbaharda şehir ve tarih turları."
    },
    "17": {
        plate: "17",
        id: "canakkale",
        name: "Çanakkale",
        regionId: "marmara",
        areaCode: "286",
        population: "560.000",
        altitude: "3 m",
        tagline: "Çanakkale Geçilmez: Zaferin ve Troya'nın Şehri",
        highlights: ["Tarihi Gelibolu Şehitliği & Anıtı", "Troya Antik Kenti ve Müzesi", "Assos Antik Kenti (Behramkale)", "Bozcaada & Gökçeada", "Aynalı Çarşı"],
        foods: ["Fırınlanmış Peynir Helvası", "Asma Yaprağında Sardalya", "Ezine Peyniri", "Çanakkale Domatesi", "Oğmaç Çorbası"],
        desc: "Tarihin dönüm noktası Çanakkale Destanı'nın yazıldığı Gelibolu Yarımadası, Homeros'un İlyada Destanı'ndaki Troya'sı ve Bozcaada'nın rüzgar gülleriyle Çanakkale bir destandır.",
        bestTime: "Şehitlik ziyaretleri için 18 Mart haftası ve ilkbahar; ada tatilleri için yaz ayları."
    },
    "18": {
        plate: "18",
        id: "cankiri",
        name: "Çankırı",
        regionId: "icanadolu",
        areaCode: "376",
        population: "195.000",
        altitude: "730 m",
        tagline: "Yerin 150 Metre Altında Tarihi Kaya Tuzu Mağarası",
        highlights: ["Tarihi Kaya Tuzu Mağarası (5000 yıllık)", "Çankırı Kalesi", "Tarihi Çamaşırhane Müzesi", "Ilgaz Dağı Kayak Merkezi", "Ferit Akalın Parkı"],
        foods: ["Yaren Güveci", "Cızlama", "Tatar Böreği", "Bumbar Dolması", "Çankırı Tuzuyla Kuru Et"],
        desc: "Hititlerden kalan 5 bin yıllık devasa Kaya Tuzu Mağarası, Ilgaz Dağları'nın çam ormanları ve köklü Yaren kültürüyle Çankırı özgün bir Anadolu şehridir.",
        bestTime: "Kışın Ilgaz Dağı kayağı; bahar aylarında Tuz Mağarası ve kültür turları."
    },
    "19": {
        plate: "19",
        id: "corum",
        name: "Çorum",
        regionId: "karadeniz",
        areaCode: "364",
        population: "525.000",
        altitude: "801 m",
        tagline: "Hitit Uygarlığının Başkenti: Hattuşa",
        highlights: ["Hattuşa (Boğazkale UNESCO)", "Yazılıkaya Açık Hava Tapınağı", "Alacahöyük Ören Yeri", "Çorum Saat Kulesi", "İncesu Kanyonu"],
        foods: ["Çorum Kavrulmuş Leblebisi", "İskilip Dolması (Ca Dolması)", "Kuru Mantı", "Çorum Baklavası", "Katmer"],
        desc: "Tarihin ilk yazılı barış antlaşması Kadeş'e imza atan Hitit İmparatorluğu'nun başkenti Hattuşa'ya ev sahipliği yapan Çorum, arkeoloji ve leblebinin merkezidir.",
        bestTime: "Hitit yolu yürüyüşleri ve antik kent turları için Mayıs - Ekim dönemi."
    },
    "20": {
        plate: "20",
        id: "denizli",
        name: "Denizli",
        regionId: "ege",
        areaCode: "258",
        population: "1.060.000",
        altitude: "354 m",
        tagline: "Beyaz Cennet Pamukkale ve Antik Havuz",
        highlights: ["Pamukkale Travertenleri (UNESCO)", "Hierapolis Antik Kenti & Kleopatra Havuzu", "Laodikeia Antik Kenti", "Kaklık Mağarası", "Teleferik & Bağbaşı Yaylası"],
        foods: ["Denizli Fırın Kebabı (Tandır)", "Zafer Gazozu", "Çameli Fasulyesi", "Kuyu Kebabı", "Tavas Pidesi"],
        desc: "Bembeyaz traverten terasları, termal antik havuzları ve tekstil geleneğiyle Denizli, doğa ve tarihin bir arada dans ettiği dünyaca ünlü bir destinasyondur.",
        bestTime: "Travertenlerde yürümek ve Hierapolis antik kentini keşfetmek için ilkbahar ve sonbahar ayları."
    },
    "21": {
        plate: "21",
        id: "diyarbakir",
        name: "Diyarbakır",
        regionId: "guneydoguanadolu",
        areaCode: "412",
        population: "1.815.000",
        altitude: "675 m",
        tagline: "Binlerce Yıllık Surlar ve Hevsel Bahçeleri",
        highlights: ["Diyarbakır Kalesi ve Surları (UNESCO)", "Hevsel Bahçeleri", "Ulu Cami (İslam'ın 5. Harem-i Şerifi)", "On Gözlü Köprü", "Hasan Paşa Hanı"],
        foods: ["Diyarbakır Kuzu Ciğer Kebabı", "Burma Kadayıf", "Meftune", "Karpuz", "Kaburga Dolması"],
        desc: "Çin Seddi'nden sonra dünyanın en uzun ve sağlam surlarına sahip olan kadim Diyarbakır, Dicle Nehri kıyısındaki bereketli Hevsel Bahçeleri ve zengin kültürüyle büyüler.",
        bestTime: "Kavurucu yaz sıcakları öncesi ve sonrası; Mart - Mayıs ile Ekim - Kasım ayları idealdir."
    },
    "22": {
        plate: "22",
        id: "edirne",
        name: "Edirne",
        regionId: "marmara",
        areaCode: "284",
        population: "415.000",
        altitude: "42 m",
        tagline: "Mimar Sinan'ın Ustalık Eseri Selimiye'nin Şehri",
        highlights: ["Selimiye Camii (UNESCO)", "Tarihi Meriç & Tunca Köprüleri", "Sultan II. Bayezid Külliyesi Sağlık Müzesi", "Kırkpınar Er Meydanı", "Eski Cami"],
        foods: ["Edirne Yaprak Tava Ciğeri", "Badem Ezmesi", "Kavala Kurabiyesi", "Edirne Beyaz Peyniri", "Hayrabolu Tatlısı"],
        desc: "Osmanlı'ya bir asra yakın başkentlik yapmış, Mimar Sinan'ın 'ustalık eserim' dediği Selimiye Camii ile taçlanan Edirne, Meriç kıyısındaki asil bir sınır şehridir.",
        bestTime: "Haziran-Temmuz aylarında Tarihi Kırkpınar Yağlı Güreşleri dönemi ve ilkbahar."
    },
    "23": {
        plate: "23",
        id: "elazig",
        name: "Elazığ",
        regionId: "doguanadolu",
        areaCode: "424",
        population: "590.000",
        altitude: "1.067 m",
        tagline: "Eğri Minareli Harput ve Mavi Hazar Gölü",
        highlights: ["Harput Kalesi & Antik Kenti", "Eğri Minareli Harput Ulu Cami", "Hazar Gölü & Batık Şehir", "Buzluk Mağarası", "Keban Baraj Gölü"],
        foods: ["Harput Köftesi", "Orcik (Cevizli Sucuk)", "Gömme", "İşgene", "Vişne Dondurması"],
        desc: "Pisa Kulesi'nden daha eğik minaresiyle meşhur Harput Kalesi, berrak sularında su sporları yapılan Hazar Gölü ile Elazığ, Doğu Anadolu'nun parlayan incisidir.",
        bestTime: "Hazar Gölü su sporları ve Harput turları için Mayıs - Eylül arası."
    },
    "24": {
        plate: "24",
        id: "erzincan",
        name: "Erzincan",
        regionId: "doguanadolu",
        areaCode: "446",
        population: "240.000",
        altitude: "1.185 m",
        tagline: "Doğa Sporları Cenneti ve Girlevik Şelalesi",
        highlights: ["Girlevik Şelalesi", "Kemaliye (Eğin) Evleri & Karanlık Kanyon", "Ergan Dağı Kayak Merkezi", "Taş Yolu", "Mama Hatun Külliyesi"],
        foods: ["Erzincan Tulum Peyniri", "Kemah Doğal Kaynak Tuzu", "Dövmeç", "Kete", "Gasefe"],
        desc: "Fırat Nehri'nin kollarından Karasu'nun geçtiği, Karanlık Kanyon'da rafting ve base jump yapılan, kışın donan Girlevik Şelalesi ile Erzincan tam bir macera rotasıdır.",
        bestTime: "Karanlık Kanyon festivalleri için Haziran - Ağustos; kayak için kış ayları."
    },
    "25": {
        plate: "25",
        id: "erzurum",
        name: "Erzurum",
        regionId: "doguanadolu",
        areaCode: "442",
        population: "750.000",
        altitude: "1.890 m",
        tagline: "Dadaşlar Diyarı, Selçuklu Anıtları ve Palandöken",
        highlights: ["Çifte Minareli Medrese", "Yakutiye Medresesi", "Palandöken Kayak Merkezi", "Erzurum Kalesi & Saat Kulesi", "Tortum Şelalesi"],
        foods: ["Erzurum Cağ Kebabı", "Kadayıf Dolması", "Lavaş & Civil Peyniri", "Su Böreği", "Ayran Aşı"],
        desc: "Palandöken Dağları'nın toz karları, Selçuklu'nun taşa işlenmiş zarafeti Çifte Minareli Medrese ve meşe odununda pişen Cağ Kebabı ile Erzurum, Doğu'nun zirvesidir.",
        bestTime: "Kış kayağı için Aralık - Nisan; yaylalar ve Tortum Şelalesi için Mayıs - Eylül."
    },
    "26": {
        plate: "26",
        id: "eskisehir",
        name: "Eskişehir",
        regionId: "icanadolu",
        areaCode: "222",
        population: "910.000",
        altitude: "788 m",
        tagline: "Venedik Havasında Modern Öğrenci ve Kültür Şehri",
        highlights: ["Tarihi Odunpazarı Evleri & Balmumu Müzesi", "Porsuk Çayı & Gondol Turları", "Sazova Bilim, Sanat ve Kültür Parkı", "Kurşunlu Külliyesi", "Yılmaz Büyükerşen Balmumu Heykeller Müzesi"],
        foods: ["Hakiki Kırım Çiböreği", "Balaban Köfte", "Met Helvası & Nuga", "Haşhaşlı Çörek", "Kalabak Suyu"],
        desc: "Porsuk Çayı üzerinde süzülen gondolları, masal şatosuna ev sahipliği yapan Sazova Parkı ve rengarenk Odunpazarı konaklarıyla Eskişehir, çağdaş bir masal şehridir.",
        bestTime: "Açık hava yürüyüşleri, park gezileri ve festival için Nisan - Kasım arası."
    },
    "27": {
        plate: "27",
        id: "gaziantep",
        name: "Gaziantep",
        regionId: "guneydoguanadolu",
        areaCode: "342",
        population: "2.155.000",
        altitude: "850 m",
        tagline: "UNESCO Tescilli Gastronomi Başkenti ve Mozaikler",
        highlights: ["Zeugma Mozaik Müzesi (Çingene Kızı)", "Gaziantep Kalesi", "Tarihi Bakırcılar Çarşısı", "Rumkale & Fırat Nehri", "Tahmis Kahvesi (1635)"],
        foods: ["Gaziantep Fıstıklı Baklavası", "Beyran Çorbası", "Ali Nazik Kebabı", "Küşleme", "Katmer", "Menengiç Kahvesi"],
        desc: "Dünyanın en büyük mozaik müzelerinden Zeugma'sı, UNESCO Gastronomi şehri unvanlı efsanevi mutfağı ve yüzyıllık bakır çekiç sesleriyle Gaziantep, bir lezzet tapınağıdır.",
        bestTime: "Gurme ve kültür turları için ilkbahar (Nisan-Mayıs) ve sonbahar (Eylül-Kasım) harikadır."
    },
    "28": {
        plate: "28",
        id: "giresun",
        name: "Giresun",
        regionId: "karadeniz",
        areaCode: "454",
        population: "450.000",
        altitude: "10 m",
        tagline: "Fındığın Başkenti ve Karadeniz'in Yaşanabilir Tek Adası",
        highlights: ["Giresun Adası", "Giresun Kalesi", "Kümbet Yaylası", "Kuzalan Şelalesi & Mavi Göl", "Zeytinlik Tarihi Mahallesi"],
        foods: ["Kaliteli Giresun Fındığı", "Karalahana Sarması & Çorbası", "Kiraz Tuzlaması Kavurması", "Fasulye Diblesi", "Pancar Çorbası"],
        desc: "Dünyanın en kaliteli fındıklarının yetiştiği, Karadeniz'deki tek yerleşilebilir ada olan Giresun Adası'nı ve turkuaz Mavi Göl'ü barındıran cennet bir kıyı şehridir.",
        bestTime: "Kümbet yayla şenlikleri ve doğa gezileri için Haziran - Eylül ayları."
    },
    "29": {
        plate: "29",
        id: "gumushane",
        name: "Gümüşhane",
        regionId: "karadeniz",
        areaCode: "456",
        population: "145.000",
        altitude: "1.150 m",
        tagline: "Pestilin Memleketi ve Karaca Mağarası Harikası",
        highlights: ["Karaca Mağarası (Damlataş harikası)", "Tomara Şelalesi (Kırk Gözeler)", "Santa Harabeleri", "Krom Vadisi", "Limni Gölü Tabiat Parkı"],
        foods: ["Gümüşhane Dut Pestili & Kömesi", "Siron", "Kete", "Kartol Yahnisi", "Ekmek Aşı"],
        desc: "Sarkıt ve dikitleriyle bilim dünyasını büyüleyen Karaca Mağarası, gürül gürül akan Tomara Şelalesi ve meşhur dut pestiliyle Gümüşhane, doğanın cömert bir köşesidir.",
        bestTime: "Şelale ve yayla manzaraları için Mayıs - Ekim ayları."
    },
    "30": {
        plate: "30",
        id: "hakkari",
        name: "Hakkâri",
        regionId: "doguanadolu",
        areaCode: "438",
        population: "280.000",
        altitude: "1.720 m",
        tagline: "Cilo Buzulları ve Dört Mevsim Karlı Zirveler",
        highlights: ["Cilo Buzul Gölleri & Reşko Tepesi", "Zap Vadisi & Taş Köprü", "Merga Bütan Kayak Merkezi", "Meydan Medresesi", "Seyithan Gölü"],
        foods: ["Doğaba", "Hakkâri Çorti Aşı", "Kemikli Kelle Paça", "Lalepet Tatlısı", "Cevizli Otlu Peynir"],
        desc: "Türkiye'nin Alpleri sayılan 4 bin metrelik Cilo Buzul Dağları, coşkun akan Zap Suyu ve el değmemiş görkemli doğasıyla Hakkâri, vahşi doğa tutkunlarının rüyasıdır.",
        bestTime: "Buzul turları ve doğa tırmanışları için Temmuz - Eylül ayları."
    },
    "31": {
        plate: "31",
        id: "hatay",
        name: "Hatay",
        regionId: "akdeniz",
        areaCode: "326",
        population: "1.685.000",
        altitude: "85 m",
        tagline: "Medeniyetler Beşiği, Saint Pierre ve Efsane Künefe",
        highlights: ["Saint Pierre Kilisesi (İlk mağara kilise)", "Titus Tüneli & Beşikli Mağara", "Habib-i Neccar Camii", "Hatay Arkeoloji Müzesi", "Vakıflı Köyü"],
        foods: ["Hatay Künefesi", "Tepsi Kebabı", "Humus", "Muhammara & Zahter", "Oruk (İçli Köfte)", "Biberli Ekmek"],
        desc: "Üç semavi dinin yüzyıllardır kardeşçe yaşadığı, Hristiyanlık adının ilk verildiği Saint Pierre Kilisesi'ne ve UNESCO gastronomi unvanına sahip Hatay, bir kültür hazinesidir.",
        bestTime: "Ilıman Akdeniz iklimi ile ilkbahar ve sonbahar ayları gezmek için en güzel vakittir."
    },
    "32": {
        plate: "32",
        id: "isparta",
        name: "Isparta",
        regionId: "akdeniz",
        areaCode: "246",
        population: "445.000",
        altitude: "1.035 m",
        tagline: "Güller ve Lavantalar Diyarı",
        highlights: ["Kuyucak Lavanta Köyü", "Eğirdir Gölü & Yeşilada", "Yazılı Kanyon Tabiat Parkı", "Davraz Dağı Kayak Merkezi", "Kovada Gölü"],
        foods: ["Isparta Fırın Kebabı", "Gül Lokumu & Gül Reçeli", "Kabune Pilavı", "Sazan Dolması", "Yalvaç Güllacı"],
        desc: "Dünya gül yağı üretiminin lideri olan Isparta, mor lavanta tarlaları, Eğirdir Gölü'nün huzurlu koyları ve kışın Davraz Kayak Merkezi ile dört mevsim renklidir.",
        bestTime: "Gül hasadı için Mayıs - Haziran; lavanta çiçekleri için Temmuz ayı büyüleyicidir."
    },
    "33": {
        plate: "33",
        id: "mersin",
        name: "Mersin",
        regionId: "akdeniz",
        areaCode: "324",
        population: "1.915.000",
        altitude: "10 m",
        tagline: "Kızkalesi, Cennet-Cehennem ve Tantuninin Şehri",
        highlights: ["Kızkalesi (Deniz Kalesi)", "Cennet - Cehennem Obrukları & Astım Mağarası", "Kanlıdivane Antik Kenti", "Tarsus Şelalesi & Eshab-ı Kehf Mağarası", "Mamure Kalesi"],
        foods: ["Mersin Tantunisi", "Cezerye", "Kerebiç (Çöven Köpüklü)", "Sıkma", "Tarsus Humusu", "Batırık"],
        desc: "Masmavi denizin ortasındaki efsanevi Kızkalesi, mitolojik derinlikteki Cennet-Cehennem obrukları, palmiyeli sahil kordonu ve damak çatlatan tantunisiyle Mersin Akdeniz'in incisidir.",
        bestTime: "Kültür ve deniz tatili için Nisan - Haziran ile Eylül - Kasım ayları."
    },
    "34": {
        plate: "34",
        id: "istanbul",
        name: "İstanbul",
        regionId: "marmara",
        areaCode: "212 / 216",
        population: "15.900.000",
        altitude: "40 m",
        tagline: "İki Kıtayı Birleştiren Dünyanın Başkenti",
        highlights: ["Ayasofya-i Kebir Cami-i Şerifi", "Topkapı Sarayı & Sultanahmet", "Galata Kulesi & İstiklal Caddesi", "İstanbul Boğazı & Kız Kulesi", "Kapalıçarşı & Mısır Çarşısı", "Dolmabahçe Sarayı & Ortaköy Sahili", "Kadıköy Moda Sahili & Çamlıca Tepesi"],
        foods: ["Sultanahmet Köftesi", "Eminönü Balık Ekmek", "Kanlıca Pudra Şekerli Yoğurdu", "Boğaz Balıkları", "Ortaköy Kumpiri & Waffle", "Süleymaniye Kuru Fasulyesi", "Karaköy Güllüoğlu Baklavası", "Sarıyer Böreği"],
        desc: "Roma, Doğu Roma ve Osmanlı İmparatorluklarına başkentlik yapmış, Asya ile Avrupa kıtalarını birbirine bağlayan masalsı Boğazı, tarihi silueti ve dinamik metropol enerjisiyle İstanbul, dünyanın en görkemli kültür ve turizm merkezidir.",
        bestTime: "Lale Festivali için Nisan ayı, Boğaz esintileri için Mayıs - Ekim ayları.",
        sides: {
            avrupa: {
                id: "istanbul-avrupa",
                name: "İstanbul (Avrupa Yakası)",
                shortName: "Avrupa Yakası",
                sideIcon: "🏰",
                areaCode: "0212",
                tagline: "Tarihi Yarımada, Boğaz Silueti & Kültürün Kalbi",
                desc: "Tarihi Yarımada'nın bin yıllık sarayları, Galata Kulesi'nin büyüleyici manzarası, canlı Beyoğlu sokakları ve Beşiktaş-Sarıyer boğaz sahil şeridiyle Avrupa Yakası, dünya tarihinin atan kalbidir.",
                highlights: [
                    "Ayasofya-i Kebir Cami-i Şerifi & Sultanahmet Camii",
                    "Topkapı Sarayı, Arkeoloji Müzeleri & Gülhane Parkı",
                    "Galata Kulesi, Karaköy & Tarihi Galata Köprüsü",
                    "İstiklal Caddesi, Taksim Meydanı & Çiçek Pasajı",
                    "Dolmabahçe Sarayı & Beşiktaş Sahil Kordonu",
                    "Ortaköy Camii & Boğaz İskelesi Meydanı",
                    "Kapalıçarşı, Beyazıt Meydanı & Mısır Çarşısı",
                    "Süleymaniye Camii & Haliç Panoraması",
                    "Rumeli Hisarı & Emirgan Korusu (Lale Festivali)",
                    "Pierre Loti Tepesi & Eyüpsultan Camii",
                    "Balat & Fener Tarihi Renkli Sokakları",
                    "Yerebatan Sarnıcı & Şerefiye Sarnıcı"
                ],
                foods: [
                    "Tarihi Sultanahmet Köftesi",
                    "Eminönü Taka Balık Ekmek & Turşu Suyu",
                    "Ortaköy Kumpiri & Özel Waffle",
                    "Süleymaniye Kuru Fasulyesi",
                    "Karaköy Güllüoğlu Baklavası",
                    "Tarihi Vefa Bozacısı",
                    "Tarihi Sarıyer Böreği",
                    "Beyoğlu Çikolatası & Profiterolü",
                    "Beşiktaş Kahvaltıcılar Sokağı Lezzetleri"
                ],
                keyDistricts: ["Fatih (Sultanahmet)", "Beyoğlu (Taksim/Galata)", "Beşiktaş", "Şişli", "Sarıyer", "Eyüpsultan", "Bakırköy"]
            },
            asya: {
                id: "istanbul-asya",
                name: "İstanbul (Anadolu / Asya Yakası)",
                shortName: "Anadolu / Asya Yakası",
                sideIcon: "⛵",
                areaCode: "0216",
                tagline: "Kız Kulesi, Huzurlu Sahiller, Tarihi Yalılar & Yaşam",
                desc: "Efsanevi Kız Kulesi, Kadıköy ve Moda'nın genç ve bohem enerjisi, Çamlıca Tepesi'nin eşsiz Boğaz manzarası, yemyeşil koruları ve huzur veren sahil kasabalarıyla Asya Yakası, İstanbul'un keyif ve huzur cennetidir.",
                highlights: [
                    "Kız Kulesi (Üsküdar Salacak Açıkları)",
                    "Kadıköy Moda Sahili, Parkı & Tarihi Moda Tramvayı",
                    "Çamlıca Tepesi & Çamlıca TV Kulesi Panoraması",
                    "Bağdat Caddesi (Alışveriş & Sahil Yürüyüşü)",
                    "Beylerbeyi Sarayı & Çengelköy Tarihi İskelesi",
                    "Anadolu Hisarı & Göksu Deresi Tekne Turları",
                    "Kuzguncuk Tarihi Ahşap Evleri & Bostanı",
                    "Fenerbahçe Parkı & Kalamış Marina",
                    "Kanlıca Sahili & Mihrabat Korusu",
                    "Polonezköy Tabiat Parkı & Cumhuriyet Köyü",
                    "Şile Deniz Feneri, Ağva Göksu Nehri & Karadeniz Sahili",
                    "Prens Adaları (Büyükada Aya Yorgi, Heybeliada)"
                ],
                foods: [
                    "Meşhur Kanlıca Pudra Şekerli Doğal Yoğurdu",
                    "Tarihi Moda Dondurması (Kadıköy)",
                    "Tarihi Çengelköy Böreği & Çengelköy Salatalığı",
                    "Üsküdar Kanaat Lokantası Osmanlı Tatlıları",
                    "Kadıköy Balıkçılar Çarşısı Taze Deniz Ürünleri",
                    "Beykoz Meşhur Kelle Paça Çorbası",
                    "Kuzguncuk Tarihi Fırın Kurabiyeleri",
                    "Ağva Alabalığı & Köy Kahvaltısı"
                ],
                keyDistricts: ["Kadıköy (Moda)", "Üsküdar", "Beykoz (Kanlıca/Göksu)", "Ataşehir", "Maltepe", "Şile & Ağva", "Adalar"]
            }
        }
    },
    "35": {
        plate: "35",
        id: "izmir",
        name: "İzmir",
        regionId: "ege",
        areaCode: "232",
        population: "4.460.000",
        altitude: "5 m",
        tagline: "Güzel İzmir: Ege'nin İncisi, Efes ve Özgürlük",
        highlights: ["Tarihi Konak Saat Kulesi & Kemeraltı", "Efes Antik Kenti (UNESCO)", "Şirince Köyü & Meryem Ana Evi", "Alaçatı & Çeşme Yarımadası", "Alsancak Kordonboyu"],
        foods: ["İzmir Boyozu & Haşlanmış Yumurta", "Çeşme Kumrusu", "İzmir Bombası", "İzmir Köftesi", "Şambali Tatlısı", "Enginar Kalbi"],
        desc: "İmbat rüzgarı, Kordon'da günbatımı neşesi, 8 bin yıllık Efes Antik Kenti, rüzgar sörfünün merkezi Alaçatı sokakları ve çıtır boyozu ile İzmir, yaşam sevinci veren bir şehirdir.",
        bestTime: "Deniz tatili için Haziran - Eylül; Efes ve kordon yürüyüşleri için Mart - Mayıs ve Ekim ayları."
    },
    "36": {
        plate: "36",
        id: "kars",
        name: "Kars",
        regionId: "doguanadolu",
        areaCode: "474",
        population: "280.000",
        altitude: "1.768 m",
        tagline: "Ani Harabeleri, Çıldır Buz Gölü ve Doğu Ekspresi",
        highlights: ["Ani Arkeolojik Alanı (1001 Kiliseli Şehir - UNESCO)", "Kars Kalesi", "Baltık Mimarisi Tarihi Konaklar", "Çıldır Gölü (Kışın Kızak Turları)", "Sarıkamış Kayak Merkezi"],
        foods: ["Kars Kaşarı & Eski Gravyer Peyniri", "Fırında Kars Kazı Pilavı", "Hangel (Mantı)", "Piti Kebabı", "Kars Balı"],
        desc: "Doğu Ekspresi'nin büyüleyici son durağı, kışın buz tutan Çıldır Gölü'nde atlı kızak keyfi, Rus Baltık mimarisi taş binaları ve dünya mirası Ani Harabeleri ile Kars tam bir efsanedir.",
        bestTime: "Masalsı kış manzarası için Aralık - Mart; yeşeren Ani yaylaları için Mayıs - Temmuz."
    },
    "37": {
        plate: "37",
        id: "kastamonu",
        name: "Kastamonu",
        regionId: "karadeniz",
        areaCode: "366",
        population: "380.000",
        altitude: "774 m",
        tagline: "Kanyonlar, Konaklar ve İstiklal Madalyalı Şehir",
        highlights: ["Kastamonu Kalesi & Saat Kulesi", "Valla Kanyonu (Dünyanın en derinlerinden)", "Horma Kanyonu & Ahşap Yürüyüş Yolu", "Ilgaz Dağı Milli Parkı", "Nasrullah Camii"],
        foods: ["Kastamonu Etli Ekmeği", "Pastırma (Taşköprü Sarımsaklı)", "Çekme Helva", "Siyez Bulguru Pilavı", "Banduma"],
        desc: "Kurtuluş Savaşı'nın simgesi İstiklal Yolu'nun kahramanı, baş döndürücü Valla ve Horma kanyonları, tarihi ahşap konakları ve antik Siyez buğdayıyla Kastamonu köklü bir vatan köşesidir.",
        bestTime: "Kanyon yürüyüşleri için Haziran - Eylül; Ilgaz kış kayağı için Aralık - Mart."
    },
    "38": {
        plate: "38",
        id: "kayseri",
        name: "Kayseri",
        regionId: "icanadolu",
        areaCode: "352",
        population: "1.440.000",
        altitude: "1.050 m",
        tagline: "Erciyes'in Eteklerinde Ticaret ve Mantı Başkenti",
        highlights: ["Erciyes Dağı Kayak Merkezi (3.917 m)", "Tarihi Kayseri Kalesi & Kapalı Çarşı", "Gevher Nesibe Şifahanesi", "Kapuzbaşı Şelaleleri (Aladağlar)", "Kültepe Kaniş-Karum"],
        foods: ["Kayseri Mantısı (Bir kaşıkta 40 adet)", "Hakiki Kayseri Pastırması & Sucuğu", "Yağlama (Şebit)", "Pöç Kebabı", "Nevzine Tatlısı"],
        desc: "Görkemli volkanik Erciyes Dağı'nın eteklerinde, 4 bin yıllık Kültepe tabletleriyle ticaretin beşiği olan Kayseri, Selçuklu şifahaneleri ve dünyaca ünlü mantısıyla damaklarda taht kurar.",
        bestTime: "Erciyes kayağı için Aralık - Nisan; Kapuzbaşı şelaleleri ve kültür turları için bahar ayları."
    },
    "39": {
        plate: "39",
        id: "kirklareli",
        name: "Kırklareli",
        regionId: "marmara",
        areaCode: "288",
        population: "370.000",
        altitude: "203 m",
        tagline: "İğneada Longoz Ormanları ve Trakya Doğası",
        highlights: ["İğneada Longoz Ormanları Milli Parkı", "Dupnisa Mağarası", "Kıyıköy Kalesi & Aya Nikola Manastırı", "Hızırbey Camii (Büyük Cami)", "Cehennem Şelaleleri"],
        foods: ["Kırklareli Köftesi", "Hardaliye (Geleneksel Üzüm İçeceği)", "Trakya Eski Kaşarı", "Süt Kuzusu Tandır", "Hayrabolu"],
        desc: "Avrupa'nın en büyük subasar (longoz) ormanlarına ev sahipliği yapan İğneada, Karadeniz kıyısındaki tarihi Kıyıköy ve nefis hardaliyesiyle Kırklareli, huzurun adresidir.",
        bestTime: "Longoz ormanında kano turları için Mayıs - Ekim; deniz için yaz ayları."
    },
    "40": {
        plate: "40",
        id: "kirsehir",
        name: "Kırşehir",
        regionId: "icanadolu",
        areaCode: "386",
        population: "245.000",
        altitude: "985 m",
        tagline: "UNESCO Müzik Şehri ve Ahiliğin Doğduğu Toprak",
        highlights: ["Cacabey Medresesi (Gökbilim Medresesi)", "Ahi Evran Camii ve Türbesi", "Kaman Kalehöyük Arkeoloji Müzesi & Japon Bahçesi", "Seyfe Gölü Kuş Cenneti", "Neşet Ertaş Gönül Sultanları Kültür Evi"],
        foods: ["Kırşehir Çullaması", "Çirleme", "Kırşehir Tandır Ekmeği", "Ahi Helvası", "Pekmezli Höşmerim"],
        desc: "Bozkırın tezenesi büyük ozan Neşet Ertaş'ın memleketi, esnaf dayanışması Ahiliğin kurucusu Ahi Evran'ın türbesi ve Selçuklu rasathanesi Cacabey ile Kırşehir gönülleri fetheder.",
        bestTime: "Ahilik Haftası kutlamaları (Eylül) ve ilkbahar ayları."
    },
    "41": {
        plate: "41",
        id: "kocaeli",
        name: "Kocaeli",
        regionId: "marmara",
        areaCode: "262",
        population: "2.080.000",
        altitude: "30 m",
        tagline: "Ormanya Doğası, Kartepe ve Pişmaniye",
        highlights: ["Ormanya Doğal Yaşam Parkı & Hobbit Evleri", "Kartepe Kayak Merkezi", "Maşukiye Şelaleleri", "Saat Kulesi & Kasr-ı Hümayun", "Kandıra Kerpe Kayalıkları"],
        foods: ["İzmit Pişmaniyesi", "Kandıra Manda Yoğurdu", "Cızlama", "Umaç Çorbası", "Yarประโยชน์ Tatlısı"],
        desc: "Avrupa'nın en büyük doğal yaşam parkı Ormanya'sı, kışın kar beyazı Kartepe'si, Karadeniz'in heykelsi Kerpe kayalıkları ve tel tel dökülen pişmaniyesiyle Kocaeli çok yönlü bir metropoldür.",
        bestTime: "Ormanya ve Maşukiye doğa kaçamakları için bahar; kış kayağı için Kartepe."
    },
    "42": {
        plate: "42",
        id: "konya",
        name: "Konya",
        regionId: "icanadolu",
        areaCode: "332",
        population: "2.300.000",
        altitude: "1.016 m",
        tagline: "Mevlana'nın Hoşgörü Diyarı ve Çatalhöyük",
        highlights: ["Mevlana Müzesi & Kubbe-i Hadra", "Çatalhöyük Neolitik Kenti (UNESCO)", "Karatay Medresesi Çini Müzesi", "Beyşehir Gölü & Eşrefoğlu Camii", "Sille Tarihi Köyü", "Tropikal Kelebek Bahçesi"],
        foods: ["Konya Etliekmeği", "Fırın Kebabı", "Tirit", "Bamya Çorbası", "Sac Arası Tatlısı", "Mevlana Şekeri"],
        desc: "'Gel, ne olursan ol yine gel' diyen Hz. Mevlana'nın türbesi, insanlığın ilk yerleşimlerinden Çatalhöyük'ü ve ahşap direkli Eşrefoğlu Camii ile Konya, ruhu dinlendiren bir ulu şehirdir.",
        bestTime: "Şeb-i Arus törenleri için 7-17 Aralık haftası; kültür turları için Nisan - Ekim."
    },
    "43": {
        plate: "43",
        id: "kutahya",
        name: "Kütahya",
        regionId: "ege",
        areaCode: "274",
        population: "580.000",
        altitude: "970 m",
        tagline: "Çininin Başkenti ve Dünyanın İlk Borsası Aizanoi",
        highlights: ["Aizanoi Antik Kenti & Zeus Tapınağı", "Kütahya Kalesi", "Tarihi Germiyan Sokağı", "Çinili Cami", "Dumlupınar Şehitliği"],
        foods: ["Sıkıcık Çorbası", "Kütahya Güveci", "Cimcik Mantısı", "Haşhaşlı Pide", "Küp Peyniri"],
        desc: "Göz nuru çinileriyle camileri, sarayları süsleyen, dünyanın ilk borsa yapısının kurulduğu görkemli Zeus Tapınaklı Aizanoi Antik Kenti'ne ev sahipliği yapan Kütahya, bir zanaat şehridir.",
        bestTime: "Aizanoi antik kenti ve tarihi sokak turları için Mayıs - Ekim ayları."
    },
    "44": {
        plate: "44",
        id: "malatya",
        name: "Malatya",
        regionId: "doguanadolu",
        areaCode: "422",
        population: "740.000",
        altitude: "964 m",
        tagline: "Dünya Kayısı Başkenti ve Aslantepe Höyüğü",
        highlights: ["Arslantepe Höyüğü (UNESCO - İlk Kerpiç Saray)", "Battalgazi Tarihi Ulu Cami", "Levent Vadisi Seyir Terası", "Tarihi Silahtar Mustafa Paşa Kervansarayı", "Günpınar Şelalesi"],
        foods: ["Malatya Altın Kayısısı", "Analı Kızlı Çorbası", "Kağıt Kebabı", "Kiraz Yaprağı Köftesi", "İçli Köfte"],
        desc: "Güneşin tadını taşıyan altın sarısı kayısıları, insanlık tarihinin ilk bürokratik devlet yapısını gösteren Arslantepe UNESCO Höyüğü ve kanyonlarıyla Malatya, Doğu'nun gururudur.",
        bestTime: "Kayısı hasadı için Temmuz ayı; kültür gezileri için Mayıs - Ekim dönemi."
    },
    "45": {
        plate: "45",
        id: "manisa",
        name: "Manisa",
        regionId: "ege",
        areaCode: "236",
        population: "1.470.000",
        altitude: "71 m",
        tagline: "Şehzadeler Şehri, Mesir Macunu ve Spil Dağı",
        highlights: ["Spil Dağı Milli Parkı & Ağlayan Kaya", "Sardes Antik Kenti (Lidya Başkenti)", "Muradiye Camii (Mimar Sinan)", "Kula Peri Bacaları & Volkanik Jeopark", "Sultan Camii"],
        foods: ["Manisa Kebabı", "Geleneksel Şifalı Mesir Macunu", "Kula Güveci", "Sultaniye Üzümü", "Simit Ekmeği"],
        desc: "Fatih Sultan Mehmet ve Kanuni Sultan Süleyman gibi padişahların yetiştiği şehzadeler şehri, paranın ilk basıldığı Sardes Antik Kenti ve şifalı Mesir Macunu Festivali ile Manisa benzersizdir.",
        bestTime: "Mesir Macunu Festivali için Mart ayı (Nevruz dönemi) ve ilkbahar."
    },
    "46": {
        plate: "46",
        id: "kahramanmaras",
        name: "Kahramanmaraş",
        regionId: "akdeniz",
        areaCode: "344",
        population: "1.120.000",
        altitude: "568 m",
        tagline: "Dövme Dondurmanın ve Milli Mücadelenin Kahraman Şehri",
        highlights: ["Kahramanmaraş Kalesi", "Tarihi Kapalı Çarşı & Bakırcılar", "Yedikuyular Kayak Merkezi", "Eshab-ı Kehf Külliyesi (Afşin)", "Taş Köprü"],
        foods: ["Hakiki Maraş Dövme Dondurması", "Maraş Tarhanası (Fırınlanmış)", "Maraş Paçası", "Eli Böğründe (Yanyana)", "Fıstıklı Ezme"],
        desc: "Sütçü İmam'ın bağımsızlık meşalesini yaktığı kahraman şehir; keçi sütü ve dağ salebiyle satırla kesilen meşhur dövme dondurması, edebiyat ekolü ve tarihi çarşılarıyla anılır.",
        bestTime: "İlkbahar ayları ve dondurma turları için Mayıs - Eylül arası."
    },
    "47": {
        plate: "47",
        id: "mardin",
        name: "Mardin",
        regionId: "guneydoguanadolu",
        areaCode: "482",
        population: "870.000",
        altitude: "1.083 m",
        tagline: "Gecesi Gerdanlık, Gündüzü Seyranlık Masal Şehir",
        highlights: ["Tarihi Mardin Taş Konakları & Sokakları", "Deyrulzafaran Manastırı", "Dara Mezopotamya Harabeleri", "Kasımiye Medresesi", "Mardin Ulu Cami"],
        foods: ["Mardin Tabağı (Sembusek & İkbebet)", "Kabab-ı Mardin", "Kaburga Dolması", "Süryani Çöreği", "Mırra Kahvesi & Badem Şekeri"],
        desc: "Mezopotamya ovasına tepeden bakan altın sarısı taş konakları, kilise çanlarıyla cami ezanlarının birbirine karıştığı engin hoşgörüsüyle Mardin, dünyada eşi benzeri olmayan bir masaldır.",
        bestTime: "Mezopotamya akşamlarını yaşamak için en güzel zaman Nisan - Mayıs ve Eylül - Kasım aylarıdır."
    },
    "48": {
        plate: "48",
        id: "mugla",
        name: "Muğla",
        regionId: "ege",
        areaCode: "252",
        population: "1.050.000",
        altitude: "660 m",
        tagline: "Mavi Turun Başkenti: Bodrum, Fethiye, Marmaris",
        highlights: ["Ölüdeniz Belcekız Plajı & Babadağ Yamaç Paraşütü", "Bodrum Kalesi & Sualtı Arkeoloji Müzesi", "Kelebekler Vadisi & Kabak Koyu", "Dalyan Kaunos Kaya Mezarları & İztuzu", "Akyaka & Azmak Çayı"],
        foods: ["Çökertme Kebabı", "Muğla Köftesi", "Bodrum Mandalinası & Reçeli", "Kabak Çiçeği Dolması", "Börülce Teretoru"],
        desc: "Türkiye'nin en uzun sahil şeridine sahip olan Muğla; Bodrum'un beyaz sokakları, Ölüdeniz'in masmavi lagünü, Dalyan'ın kral mezarları ve Azmak'ın buz gibi suyuyla tatilin zirvesidir.",
        bestTime: "Mavi tur ve deniz için Mayıs - Ekim; Babadağ yamaç paraşütü ve Likya yolu için bahar ayları."
    },
    "49": {
        plate: "49",
        id: "mus",
        name: "Muş",
        regionId: "doguanadolu",
        areaCode: "436",
        population: "400.000",
        altitude: "1.334 m",
        tagline: "Anadolu'nun Kapısı Malazgirt ve Laleler Diyarı",
        highlights: ["Tarihi Murat Köprüsü (12 Gözlü)", "Malazgirt Meydan Muharebesi Tarihi Milli Parkı", "Muş Kalesi", "Arak Manastırı", "Muş Lale Tarlaları"],
        foods: ["Muş Köftesi", "Helise (Keşkek türü)", "Hafta Et Yemeği", "Muş Balı", "Hırçikli Çorba"],
        desc: "Sultan Alparslan'ın 1071'de Anadolu kapılarını Türklere açtığı kutlu Malazgirt Ovası'na ve nisan ayında açan endemik kırmızı Muş lalelerine ev sahipliği yapar.",
        bestTime: "Muş lalelerini görmek için Nisan sonu - Mayıs başı; Malazgirt kutlamaları için 26 Ağustos."
    },
    "50": {
        plate: "50",
        id: "nevsehir",
        name: "Nevşehir",
        regionId: "icanadolu",
        areaCode: "384",
        population: "310.000",
        altitude: "1.224 m",
        tagline: "Güzel Atlar Ülkesi Kapadokya ve Peri Bacaları",
        highlights: ["Göreme Açık Hava Müzesi (UNESCO)", "Sıcak Hava Balonu Turları", "Derinkuyu & Kaymaklı Yeraltı Şehirleri", "Uçhisar Kalesi", "Avanos Çömlek Atölyeleri", "Ihlara-Paşabağları"],
        foods: ["Testi Kebabı", "Nevşehir Tavası", "Kuru Kaymak", "Düğü Çorbası", "Kapadokya Üzüm Şırası"],
        desc: "Milyonlarca yıl önce volkanik küllerin aşınmasıyla oluşan peri bacaları, gökyüzünü renklendiren sıcak hava balonları ve yeraltı şehirleriyle Kapadokya, dünyanın harikalarındandır.",
        bestTime: "Gündoğumu sıcak hava balon uçuşları ve vadilerde yürüyüş için Nisan - Kasım ayları."
    },
    "51": {
        plate: "51",
        id: "nigde",
        name: "Niğde",
        regionId: "icanadolu",
        areaCode: "388",
        population: "365.000",
        altitude: "1.229 m",
        tagline: "Aladağlar'ın Zirvesi ve Gülen Meryem Manastırı",
        highlights: ["Gümüşler Manastırı (Gülen Meryem Freski)", "Aladağlar Milli Parkı & Demirkazık", "Niğde Kalesi & Saat Kulesi", "Tyana Antik Kenti Su Kemerleri", "Narlıgöl Krater Gölü"],
        foods: ["Niğde Tavası", "Niğde Elması", "Cevizli Niğde Gazozu", "Mangır Çorbası", "Halbur Hurması"],
        desc: "Kaya içine oyulmuş eşsiz Gülen Meryem freskli Gümüşler Manastırı, dağcılık sporuyla dünyaca ünlü heybetli Aladağlar'ı ve leziz elmalarıyla Niğde, sakin ve derin bir merkezdir.",
        bestTime: "Aladağlar tırmanış ve trekking turları için Haziran - Eylül; kültür gezileri için bahar."
    },
    "52": {
        plate: "52",
        id: "ordu",
        name: "Ordu",
        regionId: "karadeniz",
        areaCode: "452",
        population: "770.000",
        altitude: "5 m",
        tagline: "Boztepe'den Karadeniz'e Bakış ve Menderesler",
        highlights: ["Boztepe & Teleferik", "Perşembe Yaylası Menderesleri", "Yason Burnu & Tarihi Kilise", "Çambaşı Kayak Merkezi", "Ünye Kalesi"],
        foods: ["Ordu Tostu", "Fırında Karalahana Çorbası", "Melocan Kavurması", "Levrek Buğulama", "Fındıklı Burma Tatlısı"],
        desc: "'Boztepe'ye çıkmalı, şu Ordu'ya bakmalı' şarkısının ilhamı, Yason Burnu'ndaki altın post efsanesi ve Perşembe Yaylası'nın kıvrım kıvrım doğa harikası menderesleriyle Ordu Karadeniz'in gözbebeğidir.",
        bestTime: "Boztepe manzarası ve yayla turları için Mayıs - Ekim ayları."
    },
    "53": {
        plate: "53",
        id: "rize",
        name: "Rize",
        regionId: "karadeniz",
        areaCode: "464",
        population: "345.000",
        altitude: "6 m",
        tagline: "Çayın Başkenti, Fırtına Vadisi ve Ayder Yaylası",
        highlights: ["Ayder Yaylası", "Fırtına Deresi & Taş Kemer Köprüler", "Zilkale & Palovit Şelalesi", "Pokut & Sal Yaylaları (Bulut Denizi)", "Rize Çay Bahçeleri & Çaykur Müzesi"],
        foods: ["Gerçek Rize Çayı", "Mıhlama (Kuymak)", "Rize Kavurması", "Hamsili Pilav", "Laz Böreği", "Anzer Balı"],
        desc: "Zümrüt yeşili dik yamaçlara serili çay tarlaları, bulut denizinin üzerinde yüzen Pokut yaylası, sarp kayalıkta yükselen Zilkale ve coşkun Fırtına Deresi ile Rize, doğanın başyapıtıdır.",
        bestTime: "Bulut denizi manzaraları ve yayla turları için Haziran - Eylül ayları."
    },
    "54": {
        plate: "54",
        id: "sakarya",
        name: "Sakarya",
        regionId: "marmara",
        areaCode: "264",
        population: "1.080.000",
        altitude: "31 m",
        tagline: "Sapanca Gölü, Acarlar Longozu ve Taraklı",
        highlights: ["Sapanca Gölü Sahili & Kırkpınar", "Acarlar Longozu (Türkiye'nin tek parça en büyüğü)", "Taraklı Tarihi Osmanlı Evleri", "Maden Deresi & Kanyonu", "Poyrazlar Gölü"],
        foods: ["Islama Köfte (Kemik sulu ekmekli)", "Kabak Tatlısı (Geyve)", "Çerkes Tavuğu", "Uğut Tatlısı", "Karasu Fındığı"],
        desc: "İstanbul'a bir nefes mesafede olan berrak Sapanca Gölü, nilüfer çiçekleriyle kaplı Acarlar Longozu ve sakin şehir (Cittaslow) unvanlı Taraklı evleriyle Sakarya, dinlendirici bir kaçış rotasıdır.",
        bestTime: "Sapanca kıyısında yürüyüş ve doğa tatili için ilkbahar ve sonbahar ayları."
    },
    "55": {
        plate: "55",
        id: "samsun",
        name: "Samsun",
        regionId: "karadeniz",
        areaCode: "362",
        population: "1.370.000",
        altitude: "20 m",
        tagline: "19 Mayıs 1919: Kurtuluş Meşalesinin Yandığı İlk Adım",
        highlights: ["Bandırma Vapuru Müzesi", "Onur Anıtı (Atatürk Heykeli)", "Şahinkaya Kanyonu (Vezirköprü)", "Kızılırmak Deltası Kuş Cenneti (UNESCO Adayı)", "Amisos Tepesi & Teleferik"],
        foods: ["Bafra Pidesi (Çıtır Kapalı)", "Terme Pidesi", "Samsun Simidi", "Nokul", "Kaz Tiridi"],
        desc: "Gazi Mustafa Kemal Atatürk'ün 19 Mayıs 1919'da ayak basarak Kurtuluş Savaşı'nı başlattığı kutsal liman Samsun, Kızılırmak Kuş Cenneti ve kanyonlarıyla Karadeniz'in en büyük merkezidir.",
        bestTime: "19 Mayıs Atatürk'ü Anma, Gençlik ve Spor Bayramı dönemi ile Haziran - Eylül."
    },
    "56": {
        plate: "56",
        id: "siirt",
        name: "Siirt",
        regionId: "guneydoguanadolu",
        areaCode: "484",
        population: "330.000",
        altitude: "895 m",
        tagline: "Tillo Bilgeleri, Veysel Karani ve Büryan",
        highlights: ["Tillo Kalesi & Cam Seyir Terası", "Veysel Karani Türbesi (Baykan)", "İsmail Fakirullah Türbesi & Işık Hadisesi", "Deliklitaş (Rasıl Hacar)", "Siirt Ulu Cami"],
        foods: ["Siirt Büryan Kebabı (Kuyu kebabı)", "Perde Pilavı", "Siirt Fıstığı", "Kitel (Siirt Köftesi)", "Zivzik Narı"],
        desc: "Astronomi ve maneviyat merkezi Tillo'daki ekinoks ışık hadisesi, uçurumun kenarındaki Deliklitaş kanyon manzarası ve fırınlarda pişen büryan kebabıyla Siirt mistik bir şehirdir.",
        bestTime: "21 Mart / 23 Eylül Tillo ışık hadisesi günleri ve ilkbahar ayları."
    },
    "57": {
        plate: "57",
        id: "sinop",
        name: "Sinop",
        regionId: "karadeniz",
        areaCode: "368",
        population: "220.000",
        altitude: "25 m",
        tagline: "Türkiye'nin En Kuzey Ucu ve Mutlu Şehir",
        highlights: ["Tarihi Sinop Kapalı Cezaevi", "Hamsilos Fiyordu (Tabiat Parkı)", "İnceburun Feneri (Türkiye'nin en kuzeyi)", "Sinop Kalesi", "Erfelek Tatlıca Şelaleleri (28 Şelale)"],
        foods: ["Cevizli ve Yoğurtlu Sinop Mantısı", "Nokul (Kıymalı/Üzümlü)", "İçli Tava (Hamsi)", "Kestaneli Pilav", "Sinop Helvası"],
        desc: "Türkiye'nin en kuzey noktası İnceburun'a sahip, Türkiye'nin tek doğal fiyordu Hamsilos'u ve şiirlere konu olan tarihi cezaeviyle Sinop, Türkiye'nin en mutlu insanlarının şehridir.",
        bestTime: "Hamsilos ve Erfelek şelalelerinde doğa yürüyüşleri için Haziran - Eylül ayları."
    },
    "58": {
        plate: "58",
        id: "sivas",
        name: "Sivas",
        regionId: "icanadolu",
        areaCode: "346",
        population: "650.000",
        altitude: "1.275 m",
        tagline: "Selçuklu Şaheseri Divriği Ulu Cami ve Kongre Şehri",
        highlights: ["Divriği Ulu Cami ve Darüşşifası (UNESCO)", "Gök Medrese & Çifte Minareli Medrese", "Buruciye Medresesi", "Kangal Balıklı Kaplıcaları", "Sivas Kongre Binası"],
        foods: ["Tescilli Sivas Köftesi", "Sivas Katmeri & Çöreği", "Hingel (Çerkes Mantısı)", "Pezik Turşusu", "Madımak Yemeği"],
        desc: "Taş işçiliğinin dünyadaki zirvesi sayılan Divriği Ulu Cami'deki mimari gölge mucizeleri, Cumhuriyetin temelinin atıldığı Sivas Kongresi ve şifalı Kangal balıklarıyla Sivas abidevi bir kenttir.",
        bestTime: "Divriği Ulu Cami ve kültür gezileri için Mayıs - Ekim ayları."
    },
    "59": {
        plate: "59",
        id: "tekirdag",
        name: "Tekirdağ",
        regionId: "marmara",
        areaCode: "282",
        population: "1.140.000",
        altitude: "10 m",
        tagline: "Marmara Kıyısında Köfte, Bağ Yolu ve Uçmakdere",
        highlights: ["Uçmakdere (Marmara Yamaç Paraşütü)", "Rüstem Paşa Külliyesi (Mimar Sinan)", "Namık Kemal Evi", "Rakoczi Müzesi", "Şarköy & Kumbağ Sahilleri"],
        foods: ["Tekirdağ Köftesi (Özel Soslu)", "Hayrabolu Tatlısı", "Tekirdağ Peynir Helvası", "Kiraz (Marmara)", "Zeytinyağlı Yaprak Sarması"],
        desc: "Ganos Dağları eteklerinden Marmara'ya yamaç paraşütü yapılan Uçmakdere'si, Mimar Sinan'ın Rüstem Paşa Külliyesi ve tescilli köftesiyle Tekirdağ, Trakya'nın sahil başkentidir.",
        bestTime: "Yamaç paraşütü, bağbozumu ve köfte turları için Mayıs - Ekim ayları."
    },
    "60": {
        plate: "60",
        id: "tokat",
        name: "Tokat",
        regionId: "karadeniz",
        areaCode: "356",
        population: "600.000",
        altitude: "623 m",
        tagline: "900 Adımda 900 Yıl: Ballıca Mağarası ve Tarih",
        highlights: ["Ballıca Mağarası (UNESCO Adayı - Soğan Sarkıtlar)", "Tokat Kalesi (Drakula'nın tutulduğu yer)", "Mahperi Hatun Kervansarayı", "Tarihi Taşhan & Yazmacılar Hanı", "Almus Baraj Gölü"],
        foods: ["Meşhur Tokat Kebabı", "Tokat Yaprağı (Bağ yaprağı)", "Çökelekli Gözleme", "Zile Pekmezi", "Bat Yemeği"],
        desc: "Nadir soğan sarkıtlarıyla dünyada benzersiz Ballıca Mağarası, Kazıklı Voyvoda'nın hapsedildiği kalesi, incecik Tokat asma yaprağı ve özel fırında pişen Tokat kebabıyla tarihi bir zenginliktir.",
        bestTime: "Tokat kebabı sezonu (yaz-sonbahar) ve Ballıca mağarası turları için Mayıs - Ekim."
    },
    "61": {
        plate: "61",
        id: "trabzon",
        name: "Trabzon",
        regionId: "karadeniz",
        areaCode: "462",
        population: "820.000",
        altitude: "35 m",
        tagline: "Sümela Manastırı, Uzungöl ve Karadeniz Fırtınası",
        highlights: ["Sümela Manastırı (Karadağ yamacında)", "Uzungöl Tabiat Parkı", "Atatürk Köşkü (Soğuksu)", "Ayasofya Camii ve Müzesi", "Boztepe Seyir Terası"],
        foods: ["Akçaabat Köftesi", "Kuymak (Kolot Peynirli)", "Hamsiköy Fırın Sütlacı", "Vakfıkebir Ekmeği", "Trabzon Tereyağı & Pidesi"],
        desc: "Sarp kayalıklara asılı duran büyüleyici Sümela Manastırı, ladin ormanlarıyla çevrili Uzungöl'ü, leziz Akçaabat köftesi ve hamsi kültürüyle Trabzon, Karadeniz'in başkentidir.",
        bestTime: "Sümela ve yayla gezileri için Mayıs - Ekim ayları."
    },
    "62": {
        plate: "62",
        id: "tunceli",
        name: "Tunceli",
        regionId: "doguanadolu",
        areaCode: "428",
        population: "85.000",
        altitude: "915 m",
        tagline: "Munzur Vadisi, Kutsal Gözeler ve Bakir Kanyonlar",
        highlights: ["Munzur Vadisi Milli Parkı", "Munzur Gözeleri (Ovacık)", "Pertek Kalesi (Kebanda ada kalesi)", "Pülümür Kanyonu & Ağlayan Kayalar", "Tunceli Kent Müzesi"],
        foods: ["Şir (Babuko)", "Organik Munzur Çiçek Balı", "Dersim Şevketi", "Zerefet", "Döğme Pilavı"],
        desc: "Billur gibi fışkıran kutsal Munzur Gözeleri, zengin endemik florası, yaban hayatı ve Keban Baraj Gölü ortasında bir ada gibi yükselen Pertek Kalesi ile Tunceli, doğanın kalbidir.",
        bestTime: "Munzur Doğa Kültür Festivali (Temmuz) ve yaz ayları."
    },
    "63": {
        plate: "63",
        id: "sanliurfa",
        name: "Şanlıurfa",
        regionId: "guneydoguanadolu",
        areaCode: "414",
        population: "2.170.000",
        altitude: "518 m",
        tagline: "Tarihin Sıfır Noktası Göbeklitepe ve Balıklıgöl",
        highlights: ["Göbeklitepe & Karahantepe (12.000 yıllık)", "Balıklıgöl (Halil-ür Rahman)", "Harran Kümbet Evleri & Dünyanın İlk İslam Üniversitesi", "Halfeti (Batık Şehir & Fırat Tekne Turu)", "Şanlıurfa Arkeoloji Müzesi"],
        foods: ["Hakiki Urfa Kebabı", "Şanlıurfa Çiğ Köftesi", "Lahmacun (İsotlu)", "Ciğer Kebabı (Sabah kahvaltısı)", "Şıllık Tatlısı", "Mırra"],
        desc: "İnsanlık tarihini yeniden yazdıran 12 bin yıllık Göbeklitepe, Hz. İbrahim'in ateşe atıldığı efsanevi Balıklıgöl ve konik kubbeli Harran evleriyle Şanlıurfa, peygamberler ve mitler diyarıdır.",
        bestTime: "Bahar ayları (Mart - Mayıs ve Ekim - Kasım) ziyaret için en keyifli zamandır."
    },
    "64": {
        plate: "64",
        id: "usak",
        name: "Uşak",
        regionId: "ege",
        areaCode: "276",
        population: "375.000",
        altitude: "907 m",
        tagline: "Dünyanın 2. En Uzun Kanyonu Ulubey ve Karun Hazineleri",
        highlights: ["Ulubey Kanyonu & Cam Teras", "Blaundos Antik Kenti", "Clandras Tarihi Su Kemeri & Şelalesi", "Uşak Arkeoloji Müzesi (Kanatlı Denizatı Broşu)", "Tarihi Uşak Evleri"],
        foods: ["Uşak Tarhana Çorbası (Coğrafi işaretli)", "Alaca Çorba", "Döndürme Böreği", "Demir Tatlısı", "Katmer"],
        desc: "Amerika'daki Büyük Kanyon'dan sonra dünyanın en uzun ikinci kanyonu olan Ulubey Kanyonu, efsanevi Karun Hazineleri ve tescilli tarhana çorbasıyla Uşak, sürprizlerle dolu bir rotadır.",
        bestTime: "Kanyon yürüyüşü ve Blaundos antik kenti fotoğrafları için Nisan - Ekim dönemi."
    },
    "65": {
        plate: "65",
        id: "van",
        name: "Van",
        regionId: "doguanadolu",
        areaCode: "432",
        population: "1.130.000",
        altitude: "1.726 m",
        tagline: "Van Denizi, Akdamar Adası ve Efsanevi Kahvaltı",
        highlights: ["Akdamar Adası ve Kutsal Haç Kilisesi", "Van Kalesi (Urartu Başkenti Tuşpa)", "Muradiye Şelalesi", "Van Kedisi Evi", "Hoşap Kalesi"],
        foods: ["Meşhur Van Kahvaltısı (30+ çeşit)", "Otlu Peynir", "İnci Kefali Balığı", "Kavut", "Murtuğa", "Kürt Köftesi"],
        desc: "Halkının 'Van Denizi' dediği Türkiye'nin en büyük gölü, üzerindeki taş işlemeleriyle büyüleyen Akdamar Kilisesi, bir gözü mavi bir gözü kehribar Van kedileri ve krallara layık kahvaltısıyla Van unutulmazdır.",
        bestTime: "İnci kefali göçü ve Akdamar badem çiçekleri için Mayıs ayı; göl gezileri için Haziran - Eylül."
    },
    "66": {
        plate: "66",
        id: "yozgat",
        name: "Yozgat",
        regionId: "icanadolu",
        areaCode: "354",
        population: "420.000",
        altitude: "1.301 m",
        tagline: "Türkiye'nin İlk Milli Parkı Çamlık ve Roma Hamamı",
        highlights: ["Yozgat Çamlığı Milli Parkı (İlk Milli Park - 1958)", "Basilica Therma (Kral Kızı Roma Hamamı)", "Çapanoğlu Camii", "Saat Kulesi", "Kazankaya Kanyonu"],
        foods: ["Yozgat Testi Kebabı", "Arabaşı Çorbası & Hamuru", "Madımak Yemeği", "Yozgat Parmak Çöreği", "İncir Uyutması"],
        desc: "Türkiye'nin ilk milli parkı unvanına sahip asırlık Çamlığı, Sarıkaya'daki 2 bin yıllık şifalı Roma Hamamı Basilica Therma ve kış akşamlarının vazgeçilmezi Arabaşı ile Yozgat samimi bir Anadolu şehridir.",
        bestTime: "Çamlık doğa turları ve Roma hamamı ziyaretleri için Mayıs - Ekim ayları."
    },
    "67": {
        plate: "67",
        id: "zonguldak",
        name: "Zonguldak",
        regionId: "karadeniz",
        areaCode: "372",
        population: "590.000",
        altitude: "15 m",
        tagline: "Karaelmas Diyarı, Kömür Madenleri ve Gökgöl",
        highlights: ["Zonguldak Maden Müzesi & Eğitim Ocağı", "Gökgöl Mağarası", "Filyos Kalesi & Tieion Antik Kenti", "Harmankaya Kanyonu", "Varagel Tüneli"],
        foods: ["Uğmaç Çorbası", "Zonguldak Kestanesi", "Malay Tatlısı", "Cevizli Kömeç", "Mancarlı Pide"],
        desc: "Türkiye'nin ağır sanayisine can veren karaelmas taş kömürü ocakları, Türkiye'nin ilk maden müzesi, Filyos antik kenti ve rengarenk sarkıtlı Gökgöl Mağarası ile Zonguldak emek ve doğa şehridir.",
        bestTime: "Mağara ve sahil gezileri için Mayıs - Eylül arası."
    },
    "68": {
        plate: "68",
        id: "aksaray",
        name: "Aksaray",
        regionId: "icanadolu",
        areaCode: "382",
        population: "435.000",
        altitude: "980 m",
        tagline: "Ihlara Vadisi Kanyonu ve Selime Katedrali",
        highlights: ["Ihlara Vadisi & Melendiz Çayı Kanyonu", "Selime Katedrali & Manastırı", "Sultanhanı Kervansarayı (En büyük Selçuklu hanı)", "Hasan Dağı (3.268 m)", "Narlıgöl Krater Gölü"],
        foods: ["Aksaray Tava", "Sıkma & Çörek", "Şerbetli Şekerpare", "Kapadokya Güveci", "Köpük Helvası"],
        desc: "Kapadokya'nın en görkemli kanyonu Ihlara Vadisi'nde Melendiz Çayı boyu dizilen kaya kiliseleri, Star Wars filmlerini andıran Selime Katedrali ve heybetli Hasan Dağı ile Aksaray büyüleyicidir.",
        bestTime: "Ihlara Vadisi'nde 14 kilometrelik doğa yürüyüşü için Nisan - Ekim ayları."
    },
    "69": {
        plate: "69",
        id: "bayburt",
        name: "Bayburt",
        regionId: "karadeniz",
        areaCode: "458",
        population: "85.000",
        altitude: "1.550 m",
        tagline: "Avrupa Müze Ödüllü Baksı ve Çoruh Kıyısı",
        highlights: ["Baksı Müzesi (Avrupa Konseyi Ödüllü)", "Kenan Yavuz Etnografya Müzesi", "Bayburt Kalesi (Çinimaçin)", "Dede Korkut Türbesi", "Sırakayalar Şelalesi"],
        foods: ["Bayburt Lor Dolması", "Galacoş", "Su Böreği", "Tatlı Çorba", "Kete"],
        desc: "Çoruh Nehri kenarında kurulan, geleneksel ile çağdaş sanatı harmanlayarak Avrupa'da yılın müzesi ödülünü kazanan Baksı Müzesi ve Dede Korkut mirasıyla Bayburt kültür cennetidir.",
        bestTime: "Baksı Müzesi ve şelale gezileri için Haziran - Eylül ayları."
    },
    "70": {
        plate: "70",
        id: "karaman",
        name: "Karaman",
        regionId: "icanadolu",
        areaCode: "338",
        population: "260.000",
        altitude: "1.033 m",
        tagline: "Türkçenin Başkenti, Yunus Emre ve Taşkale",
        highlights: ["Karaman Kalesi", "Taşkale Tarihi Tahıl Ambarları (Kaya oyma)", "İncesu Mağarası", "Manazan Mağaraları", "Hatuniye Medresesi", "Yunus Emre Türbesi"],
        foods: ["Karaman Arabaşı", "Guymak", "Töğmeken", "Batırık", "Divle Obruk Peyniri (Kırmızı tulum)"],
        desc: "Karamanoğlu Mehmet Bey'in 'Türkçeden başka dil konuşulmaya' fermanıyla Türkçenin başkenti olan, kaya oyma Taşkale ambarları ve mağaralarda olgunlaşan Divle Obruk peyniriyle Karaman eşsizdir.",
        bestTime: "Türk Dil Bayramı (Mayıs) ve sonbahar ayları."
    },
    "71": {
        plate: "71",
        id: "kirikkale",
        name: "Kırıkkale",
        regionId: "icanadolu",
        areaCode: "318",
        population: "275.000",
        altitude: "718 m",
        tagline: "Silah Sanayisinin Merkezi ve Tarihi Çeşnigir Köprüsü",
        highlights: ["MKE Silah Sanayi Müzesi", "Tarihi Çeşnigir Köprüsü ve Kanyonu", "Sulu Mağara (Keskin)", "Hasandede Camii ve Türbesi", "Karaahmetli Tabiat Parkı"],
        foods: ["Keskin Tavası", "Tuvalak", "Besmeç", "Kızılırmak Sazanı", "Madımak"],
        desc: "Kızılırmak üzerindeki Selçuklu yadigarı Çeşnigir Köprüsü, Türkiye'nin savunma sanayi mirasını yaşatan MKE Silah Müzesi ve leziz Keskin tavasıyla Kırıkkale dinamik bir merkezdir.",
        bestTime: "Çeşnigir kanyonunda tekne turu ve yürüyüş için Nisan - Ekim arası."
    },
    "72": {
        plate: "72",
        id: "batman",
        name: "Batman",
        regionId: "guneydoguanadolu",
        areaCode: "488",
        population: "635.000",
        altitude: "550 m",
        tagline: "Hasankeyf: 12 Bin Yıllık Mağaralar ve Dicle Kıyısı",
        highlights: ["Hasankeyf Antik Kenti & Yeni Kültür Parkı", "Zeynel Bey Türbesi", "Malabadi Köprüsü (Türkülerin köprüsü)", "Mor Kiryakus Manastırı", "Kozluk Kalesi"],
        foods: ["Şam Börek", "Mumbar Dolması", "Batman Kuzu Tandırı", "Kaburga Dolması", "Tırşık"],
        desc: "Dicle Nehri kenarında 12 bin yıllık mağara yerleşimleriyle insanlık hafızası Hasankeyf'i, şarkılara konu olan devasa kemerli Malabadi Köprüsü ve petrol kuyularıyla Batman tarihi bir kavşaktır.",
        bestTime: "Dicle kıyısında tekne turu ve Hasankeyf ziyareti için ilkbahar ve sonbahar."
    },
    "73": {
        plate: "73",
        id: "sirnak",
        name: "Şırnak",
        regionId: "guneydoguanadolu",
        areaCode: "486",
        population: "560.000",
        altitude: "1.350 m",
        tagline: "Nuh'un Gemisi'nin İndiği Cudi Dağı ve Kırmızı Medrese",
        highlights: ["Cudi Dağı (Hz. Nuh'un Gemisi Efsanesi)", "Kırmızı Medrese (Cizre)", "Mem u Zin Türbesi (Aşkın simgesi)", "İsmail Ebul-İz El-Cezeri Müzesi", "Kasrik Boğazı"],
        foods: ["Kutlık (İçli köfte)", "Suryaz Yemeği", "Meyre (Ayran aşı)", "Kipe", "Birkut"],
        desc: "Robotik ve sibernetiğin babası El-Cezeri'nin memleketi Cizre'si, aşk efsanesi Mem u Zin'i ve tufandan sonra hayatın yeniden başladığı rivayet edilen kutsal Cudi Dağı ile Şırnak kadim bir coğrafyadır.",
        bestTime: "Cizre kültür turları ve Kasrik Boğazı için Nisan - Mayıs ve Ekim - Kasım."
    },
    "74": {
        plate: "74",
        id: "bartin",
        name: "Bartın",
        regionId: "karadeniz",
        areaCode: "378",
        population: "205.000",
        altitude: "25 m",
        tagline: "Amasra: Çeşm-i Cihan (Dünyanın Gözü) ve Ahşap Tekneler",
        highlights: ["Amasra Kalesi & Kemere Köprüsü", "Güzelcehisar Lav Sütunları (80 milyon yıllık)", "İnkumu Plajı", "Küre Dağları Milli Parkı", "Tarihi Çekiciler Çarşısı"],
        foods: ["Amasra Özel Salatası (25+ malzemeli)", "Taze Karadeniz Balığı", "Pumpum Çorbası", "Bartın Su Böreği", "Gözleme"],
        desc: "Fatih Sultan Mehmet'in tepeden bakıp 'Çeşm-i Cihan bu mu ola?' dediği büyüleyici Amasra Yarımadası, 80 milyon yıllık lav sütunları ve ormanlarıyla Bartın bir Karadeniz rüyasıdır.",
        bestTime: "Amasra kalesinde günbatımı ve balık ziyafeti için Mayıs - Ekim ayları."
    },
    "75": {
        plate: "75",
        id: "ardahan",
        name: "Ardahan",
        regionId: "doguanadolu",
        areaCode: "478",
        population: "95.000",
        altitude: "1.829 m",
        tagline: "Kafkasların Kapısı, Şeytan Kalesi ve Çıldır",
        highlights: ["Şeytan Kalesi (Kanyon yamacında kartal yuvası)", "Çıldır Gölü Sahili", "Ardahan Kalesi (Kura Nehri kıyısında)", "Bülbülan Yaylası", "Yalnızçam Kayak Merkezi"],
        foods: ["Ardahan Çiçek Balı (Kafkas Arısı)", "Ardahan Kaşar Peyniri", "Fırında Kaz Eti", "Helle Çorbası", "Katmer"],
        desc: "Kura Nehri'nin kıvrılarak aktığı derin kanyonların ortasındaki sarp Şeytan Kalesi, saf Kafkas arılarının ürettiği coğrafi işaretli balı ve Çıldır Gölü'nün buz kristalleriyle Ardahan sınırın incisidir.",
        bestTime: "Kışın Çıldır Gölü üzerinde atlı kızak için Ocak - Mart; yaylalar için Temmuz - Ağustos."
    },
    "76": {
        plate: "76",
        id: "igdir",
        name: "Iğdır",
        regionId: "doguanadolu",
        areaCode: "476",
        population: "210.000",
        altitude: "858 m",
        tagline: "Doğu'nun Çukurovası: Pamuk, Kayısı ve Üç Ülkeye Komşu",
        highlights: ["Tuzluca Tuz Mağaraları (Tuz Terapi Merkezi)", "Ağrı Dağı Milli Parkı Kuzey Yamacı", "Karakale Ören Yeri", "İğdır Kervansarayı", "Soykırım Anıtı ve Müzesi"],
        foods: ["Bozbaş (Piti Kebabı)", "Taş Köfte", "Iğdır Al Kayısısı", "Katyık Çorbası", "Kefli Kebap"],
        desc: "Ermenistan, Nahçıvan ve İran olmak üzere üç ülkeye sınır komşusu olan, mikroklima iklimiyle Doğu Anadolu'nun pamuk ve kayısı bahçesi sayılan Iğdır, Tuzluca'nın devasa tuz mağaralarıyla ünlüdür.",
        bestTime: "Tuzluca mağaralarını ziyaret ve kayısı bahçeleri için Mayıs - Ekim ayları."
    },
    "77": {
        plate: "77",
        id: "yalova",
        name: "Yalova",
        regionId: "marmara",
        areaCode: "226",
        population: "300.000",
        altitude: "30 m",
        tagline: "Atatürk'ün Yürüyen Köşkü ve Şifalı Termal Kaplıcaları",
        highlights: ["Yürüyen Köşk (Bir çınar dalı için yürütülen köşk)", "Yalova Termal Kaplıcaları & Atatürk Köşkü", "Sudüşen Şelalesi", "Erikli Yaylası & Çifte Şelaleler", "Karaca Arboretumu (Canlı Ağaç Müzesi)"],
        foods: ["Yalova Sütlüsü Tatlısı", "Termal Tatlısı", "Yalova Köftesi", "Pavli (Haşlanmış Lahana)", "Böğürtlen Reçeli"],
        desc: "Ulu Önder Atatürk'ün bir çınar dalını kesmemek için raylar üzerinde yürüttüğü Yürüyen Köşk'ü, Roma döneminden beri şifa dağıtan termal kaplıcaları ve arboretumuyla Yalova yeşilin merkezidir.",
        bestTime: "Termal şifa ve doğa yürüyüşleri için ilkbahar ve sonbahar; sahil için yaz."
    },
    "78": {
        plate: "78",
        id: "karabuk",
        name: "Karabük",
        regionId: "karadeniz",
        areaCode: "370",
        population: "250.000",
        altitude: "280 m",
        tagline: "UNESCO Mirası Safranbolu Evleri ve Safran Çiçeği",
        highlights: ["Tarihi Safranbolu Konakları (UNESCO)", "Kristal Cam Teras & Tokatlı Kanyonu", "Bulak Mencilis Mağarası", "Yörük Köyü Tarihi Konakları", "İncekaya Su Kemeri"],
        foods: ["Safranbolu Hakiki Safranı & Lokumu", "Bükme Pidesi", "Peruhi (Mantı)", "Kuyu Kebabı", "Safranlı Zerde Tatlısı"],
        desc: "Osmanlı kent mimarisini kusursuz koruyan ahşap cumbalı Safranbolu evleri, dünyanın en pahalı baharatı safran tarlaları ve Tokatlı Kanyonu üzerindeki kristal terasıyla Karabük zamanda yolculuktur.",
        bestTime: "Safran hasadı için Ekim - Kasım; Safranbolu sokaklarında nostalji için ilkbahar."
    },
    "79": {
        plate: "79",
        id: "kilis",
        name: "Kilis",
        regionId: "guneydoguanadolu",
        areaCode: "348",
        population: "150.000",
        altitude: "640 m",
        tagline: "Zeytinin Anavatanı ve Kilis Tava Lezzeti",
        highlights: ["Ravanda Kalesi (Tarihi tepe kalesi)", "Tarihi Kilis Konakları & Kabaltılar", "Oylum Höyük (5500 yıllık)", "Ulu Cami & Salih Ağa Kasteli", "Söğütlü Dere"],
        foods: ["Meşhur Kilis Tavası", "Cennet Çamuru Tatlısı", "Kilis Zeytinyağı", "Oruk & Şıhılmahşi", "Gerebiç"],
        desc: "Bereketli zeytinlikleri, daracık sokakları örten taş kemerli kabaltıları, tarihi konakları ve fırından yeni çıkmış nefis Kilis Tavası ile Kilis, Güneydoğu'nun samimi lezzet durağıdır.",
        bestTime: "Zeytin hasadı ve gastronomi turları için Ekim - Kasım ve ilkbahar."
    },
    "80": {
        plate: "80",
        id: "osmaniye",
        name: "Osmaniye",
        regionId: "akdeniz",
        areaCode: "328",
        population: "560.000",
        altitude: "125 m",
        tagline: "Kaleler Şehri, Karatepe Hitit Yazıtları ve Yer Fıstığı",
        highlights: ["Karatepe-Aslantaş Açık Hava Müzesi (Hitit Hiyeroglifleri)", "Toprakkale Kalesi", "Kadirli Ala Cami", "Zorkun Yaylası", "Harun Reşit Kalesi"],
        foods: ["Osmaniye Yer Fıstığı", "Tirşik Çorbası (Andırın doktoru)", "Etli Kömeç", "Kadirli Sucuk Ekmeği", "Karakuş Tatlısı"],
        desc: "Hitit hiyerogliflerinin çözüldüğü anahtar yer olan Karatepe Aslantaş Açık Hava Müzesi, Çukurova'yı gözleyen onlarca tarihi kalesi ve tescilli yer fıstığıyla Osmaniye gururlu bir ildir.",
        bestTime: "Karatepe ve yayla turları için Nisan - Haziran ile Eylül - Kasım."
    },
    "81": {
        plate: "81",
        id: "duzce",
        name: "Düzce",
        regionId: "karadeniz",
        areaCode: "380",
        population: "405.000",
        altitude: "160 m",
        tagline: "Şelaleler Kenti, Rafting ve Karadeniz Kıyısı Akçakoca",
        highlights: ["Güzeldere Şelalesi Tabiat Parkı", "Samandere Şelalesi Tabiat Anıtı", "Akçakoca Ceneviz Kalesi & Sahili", "Melen Çayı Rafting Parkuru", "Topuk Yaylası & Göleti"],
        foods: ["İsli Düzce Köftesi", "Melengüçceği Tatlısı", "Konuralp Pirinci Pilavı", "Düzce Fındığı", "Mancar Otu Yemeği"],
        desc: "Güzeldere ve Samandere gibi çağıldayan şelaleleri, Melen Çayı'nda adrenalin dolu rafting heyecanı ve Karadeniz kıyısındaki mavi bayraklı Akçakoca sahiliyle Düzce doğanın kucağıdır.",
        bestTime: "Melen Çayı'nda rafting ve şelale yürüyüşleri için Nisan - Ekim arası."
    }
};

// Yardımcı fonksiyonlar
function getProvinceByPlate(plate) {
    const formatted = String(plate).padStart(2, '0');
    return PROVINCES_DATA[formatted] || null;
}

function getProvinceById(id) {
    if (!id) return null;
    const cleanId = id.toLowerCase().replace(/[^a-z0-9]/g, '');
    if (cleanId.includes('istanbul')) return PROVINCES_DATA["34"];
    for (const key in PROVINCES_DATA) {
        const p = PROVINCES_DATA[key];
        const pId = p.id.toLowerCase().replace(/[^a-z0-9]/g, '');
        if (pId === cleanId) return p;
    }
    return null;
}

function getProvinceByName(name) {
    if (!name) return null;
    const cleanName = name.toLowerCase()
        .replace(/ı/g, 'i').replace(/ğ/g, 'g').replace(/ü/g, 'u')
        .replace(/ş/g, 's').replace(/ö/g, 'o').replace(/ç/g, 'c')
        .replace(/[^a-z0-9]/g, '');
    for (const key in PROVINCES_DATA) {
        const p = PROVINCES_DATA[key];
        const pClean = p.name.toLowerCase()
            .replace(/ı/g, 'i').replace(/ğ/g, 'g').replace(/ü/g, 'u')
            .replace(/ş/g, 's').replace(/ö/g, 'o').replace(/ç/g, 'c')
            .replace(/[^a-z0-9]/g, '');
        if (pClean === cleanName) return p;
    }
    return null;
}

// 81 İl Harita İsim ve Punto Ayarları (Şehrin büyüklüğüne göre puntolar)
const PROVINCE_LABEL_CONFIG = {
    "01": { label: "Adana", size: 6.8 },
    "02": { label: "Adıyaman", size: 5.8 },
    "03": { label: "Afyon", size: 6.5 },
    "04": { label: "Ağrı", size: 6.8 },
    "05": { label: "Amasya", size: 5.2 },
    "06": { label: "Ankara", size: 8.5 },
    "07": { label: "Antalya", size: 8.5 },
    "08": { label: "Artvin", size: 5.6 },
    "09": { label: "Aydın", size: 6.0 },
    "10": { label: "Balıkesir", size: 7.0 },
    "11": { label: "Bilecik", size: 4.8 },
    "12": { label: "Bingöl", size: 5.8 },
    "13": { label: "Bitlis", size: 5.4 },
    "14": { label: "Bolu", size: 5.8 },
    "15": { label: "Burdur", size: 5.5 },
    "16": { label: "Bursa", size: 6.8 },
    "17": { label: "Çanakkale", size: 5.6, dx: -6 },
    "18": { label: "Çankırı", size: 5.5 },
    "19": { label: "Çorum", size: 6.2 },
    "20": { label: "Denizli", size: 6.4 },
    "21": { label: "Diyarbakır", size: 7.5 },
    "22": { label: "Edirne", size: 5.5 },
    "23": { label: "Elazığ", size: 5.8 },
    "24": { label: "Erzincan", size: 6.8 },
    "25": { label: "Erzurum", size: 8.5 },
    "26": { label: "Eskişehir", size: 7.2 },
    "27": { label: "G.Antep", size: 6.2 },
    "28": { label: "Giresun", size: 5.2 },
    "29": { label: "Gümüşhane", size: 5.0 },
    "30": { label: "Hakkâri", size: 6.2 },
    "31": { label: "Hatay", size: 5.8 },
    "32": { label: "Isparta", size: 5.8 },
    "33": { label: "Mersin", size: 7.0 },
    "34": { label: "İstanbul", size: 6.2, dx: -3, dy: -3 },
    "34-avrupa": { label: "İstanbul", size: 6.2, dx: -3, dy: -3 },
    "34-asya": { label: "Asya", size: 4.5, dx: 1, dy: 1 },
    "35": { label: "İzmir", size: 7.0 },
    "36": { label: "Kars", size: 6.5 },
    "37": { label: "Kastamonu", size: 7.2 },
    "38": { label: "Kayseri", size: 7.8 },
    "39": { label: "Kırklareli", size: 5.6 },
    "40": { label: "Kırşehir", size: 5.5 },
    "41": { label: "Kocaeli", size: 4.8 },
    "42": { label: "Konya", size: 9.5 },
    "43": { label: "Kütahya", size: 6.8 },
    "44": { label: "Malatya", size: 6.8 },
    "45": { label: "Manisa", size: 7.0 },
    "46": { label: "K.Maraş", size: 6.8 },
    "47": { label: "Mardin", size: 6.6 },
    "48": { label: "Muğla", size: 7.2 },
    "49": { label: "Muş", size: 5.8 },
    "50": { label: "Nevşehir", size: 5.2 },
    "51": { label: "Niğde", size: 5.8 },
    "52": { label: "Ordu", size: 5.4 },
    "53": { label: "Rize", size: 5.2 },
    "54": { label: "Sakarya", size: 5.2 },
    "55": { label: "Samsun", size: 6.5 },
    "56": { label: "Siirt", size: 5.2 },
    "57": { label: "Sinop", size: 5.4 },
    "58": { label: "Sivas", size: 8.5 },
    "59": { label: "Tekirdağ", size: 5.8 },
    "60": { label: "Tokat", size: 6.0 },
    "61": { label: "Trabzon", size: 5.4 },
    "62": { label: "Tunceli", size: 5.2 },
    "63": { label: "Şanlıurfa", size: 8.2 },
    "64": { label: "Uşak", size: 5.4 },
    "65": { label: "Van", size: 8.2 },
    "66": { label: "Yozgat", size: 6.8 },
    "67": { label: "Zonguldak", size: 4.8 },
    "68": { label: "Aksaray", size: 5.8 },
    "69": { label: "Bayburt", size: 4.6 },
    "70": { label: "Karaman", size: 6.0 },
    "71": { label: "Kırıkkale", size: 4.8 },
    "72": { label: "Batman", size: 5.2 },
    "73": { label: "Şırnak", size: 5.8 },
    "74": { label: "Bartın", size: 4.6 },
    "75": { label: "Ardahan", size: 5.4 },
    "76": { label: "Iğdır", size: 4.8 },
    "77": { label: "Yalova", size: 4.2 },
    "78": { label: "Karabük", size: 4.8 },
    "79": { label: "Kilis", size: 4.5 },
    "80": { label: "Osmaniye", size: 4.8 },
    "81": { label: "Düzce", size: 4.6 }
};
